version: '2'
services:
    db:
        image: sameersbn/mysql
        volumes:
            - "./data:/var/lib/mysql"
        environment:
            - DB_NAME=demoDb
            - DB_USER=demoUser
            - DB_PASS=demoPass
        ports:
            - "33060:3306"
    php:
        image: edyonil/php7fpm-phalcon
        volumes:
            - ./:/home/projeto
    web:
        image: nginx:latest
        links:
            - db
            - php
        ports:
            - "8080:80"
        volumes:
            - ./:/home/projeto
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        environment:
            DB_HOST: db:33060
